name: Unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Python ${{ matrix.env.python }} | ${{ matrix.env.TOXENV }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version:
        - 3.9
        - '3.10'
        - '3.11'
        - '3.12'
        - '3.13'

    steps:
      - uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tox
        run: pip install tox

      - name: Run tox targets for ${{ matrix.python-version }}
        run: tox run -f py$(echo ${{ matrix.python-version }} | tr -d .)
