name: Unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Python ${{ matrix.env.python }} | ${{ matrix.env.TOXENV }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        env:
          - python: 3.8
            TOXENV: py38-django32-drf3

          - python: 3.9
            TOXENV: py39-django32-drf3
          - python: 3.9
            TOXENV: py39-django41-drf3
          - python: 3.9
            TOXENV: py39-django42-drf3

          - python: '3.10'
            TOXENV: py310-django32-drf3
          - python: '3.10'
            TOXENV: py310-django41-drf3
          - python: '3.10'
            TOXENV: py310-django42-drf3

          - python: '3.11'
            TOXENV: py311-django41-drf3
          - python: '3.11'
            TOXENV: py311-django42-drf3


    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.env.python }}
      - name: Install tox
        run: pip install tox
      - name: Run Tests
        env:
          TOXENV: django${{ matrix.env.TOXENV }}
        run: tox -e ${{ matrix.env.TOXENV }}
